
package selectcontract;


import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/**
 * @author wenlong
 */
public class ViewBids extends javax.swing.JDialog {
    String line = "";
    JSONArray bidsArr;
    private static int currentBidNum = 0;


    public ViewBids() {
        initComponents();
    }

    public void showBids() {
        int bidCount = bidsArr.size();
        jLabelBottomLeft.setText((currentBidNum + 1) + " out of " + bidCount + " Contracts");
        if (bidCount >= 0) {
            JSONObject currentBid = (JSONObject) bidsArr.get(currentBidNum);
            String operator = (String) currentBid.get("operator");
            String bidId = (String) currentBid.get("contractID");
            String originCity = (String) currentBid.get("originCity");
            String destCity = (String) currentBid.get("destCity");
            Long bidamountlong = (long) currentBid.get("amount");
            int amount = bidamountlong.intValue();
            String orderItem = (String) currentBid.get("orderItem");
            String time = (String) currentBid.get("Time");

            jLabel2bidID.setText(bidId);
            jLabelOCITY.setText(originCity);
            jLabeldCITY.setText(destCity);
            jLabeloITEM.setText(orderItem);
            jLabeloAMOUNT.setText(Integer.toString(amount));
            jLabeloOPERATOR.setText(operator);
            jLabeloTIME.setText(time);

        }

    }

    public void setBids(JSONArray array) {
        this.bidsArr = array;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelBottomLeft = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonNextBID = new javax.swing.JButton();
        jButtonPrevBID = new javax.swing.JButton();
        jButtoncacelBids = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2bidID = new javax.swing.JLabel();
        jLabelOCITY = new javax.swing.JLabel();
        jLabeldCITY = new javax.swing.JLabel();
        jLabeloITEM = new javax.swing.JLabel();
        jLabeloAMOUNT = new javax.swing.JLabel();
        jLabeloOPERATOR = new javax.swing.JLabel();
        jLabeloTIME = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("view bids");

        jLabelBottomLeft.setText("jLabel1");

        jButtonNextBID.setText("next");
        jButtonNextBID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextBIDActionPerformed(evt);
            }
        });

        jButtonPrevBID.setText("prev");
        jButtonPrevBID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevBIDActionPerformed(evt);
            }
        });

        jButtoncacelBids.setText("cancel");
        jButtoncacelBids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncacelBidsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonPrevBID)
                                .addGap(18, 18, 18)
                                .addComponent(jButtoncacelBids)
                                .addGap(15, 15, 15)
                                .addComponent(jButtonNextBID)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonNextBID)
                                        .addComponent(jButtonPrevBID)
                                        .addComponent(jButtoncacelBids))
                                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2bidID.setText("bidID");

        jLabelOCITY.setText("oCITY");

        jLabeldCITY.setText("dCity");

        jLabeloITEM.setText("oITEM");

        jLabeloAMOUNT.setText("oAmount");

        jLabeloOPERATOR.setText("oOPERATOR");

        jLabeloTIME.setText("oTIME");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabeloTIME)
                                        .addComponent(jLabeloOPERATOR)
                                        .addComponent(jLabeloITEM)
                                        .addComponent(jLabeldCITY)
                                        .addComponent(jLabel2bidID, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelOCITY, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabeloAMOUNT, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2bidID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelOCITY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabeldCITY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabeloITEM)
                                .addGap(18, 18, 18)
                                .addComponent(jLabeloAMOUNT)
                                .addGap(18, 18, 18)
                                .addComponent(jLabeloOPERATOR)
                                .addGap(18, 18, 18)
                                .addComponent(jLabeloTIME)
                                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setText("contractID");

        jLabel3.setText("originCity");

        jLabel4.setText("destCity");

        jLabel5.setText("orderItem");

        jLabel6.setText("operator");

        jLabel7.setText("Time");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel4))
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabelBottomLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(391, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(53, 53, 53)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(74, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(66, 66, 66)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelBottomLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNextBIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextBIDActionPerformed
        System.out.println("currentBidNum: nextbtn performmed " + currentBidNum);
        System.out.println("bidsarr " + JSONArray.toJSONString(bidsArr));
        if (currentBidNum < bidsArr.size() - 1) {
            currentBidNum++;
            jButtonPrevBID.setEnabled(true);
            showBids();
        }else {
            jButtonNextBID.setEnabled(false);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNextBIDActionPerformed

    private void jButtonPrevBIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevBIDActionPerformed

        if (currentBidNum > 0) {
            jButtonNextBID.setEnabled(true);
            currentBidNum--;
            showBids();
        }else {
            jButtonPrevBID.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrevBIDActionPerformed

    private void jButtoncacelBidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncacelBidsActionPerformed
        currentBidNum = 0;
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtoncacelBidsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBids.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBids.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBids.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBids.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewBids dialog = new ViewBids();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNextBID;
    private javax.swing.JButton jButtonPrevBID;
    private javax.swing.JButton jButtoncacelBids;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2bidID;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelBottomLeft;
    private javax.swing.JLabel jLabelOCITY;
    private javax.swing.JLabel jLabeldCITY;
    private javax.swing.JLabel jLabeloAMOUNT;
    private javax.swing.JLabel jLabeloITEM;
    private javax.swing.JLabel jLabeloOPERATOR;
    private javax.swing.JLabel jLabeloTIME;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
